filter:
excluded_paths:
    - 'tests/wordpress-tests-lib/*'
    - 'public/js/*'
    - 'public/css/*'

tools:
php_code_sniffer:
    config:
        standard: WordPress
checks:
    php: true
build:
    environment:
            php:
                version: 7.2
    dependencies:
        before:
            - composer require phpunit/phpunit:^7.0 --dev
    tests:
        override:
            -
                command: vendor/bin/phpunit --coverage-clover=clover.xml
                coverage:
                    file: clover.xml
                    format: php-clover